#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged

workflow_files_count="$(git ls-files -s workflows/**/*.{libsonnet,jsonnet} | wc -l)"
if [[ "${workflow_files_count}" -gt 0 ]]
then
  npm run workflows
  git add .github/workflows
fi

action_files_count="$(git ls-files -s actions/*/src/**/*.{js,ts} | wc -l)"
if [[ "${action_files_count}" -gt 0 ]]
then
  npm run workflows
  git add actions/*/dist
fi
