#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

yarn exec -- lint-staged

workflow_files_count="$(git diff --name-only --cached workflows/*.{libsonnet,jsonnet} | wc -l)"
if [[ "${workflow_files_count}" -gt 0 ]]; then
	yarn run workflows
	git add .github/workflows
fi

action_files_count="$(git diff --name-only --cached actions/**/*.{js,ts} | wc -l)"
if [[ "${action_files_count}" -gt 0 ]]; then
	yarn run actions
	git add actions/*/dist
fi
