---
name: build loki image
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 8 * * *" # daily at 8am, but how to specify branch name?
  push:
    branches:
      - "release-[0-9].[0-9].x"
      - "k[0-9]*"

jobs:
  loki-image:
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
      - check
    steps:
      - name: pull loki code
        uses: actions/checkout@v3
        with:
          repository: grafana/loki
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.21.3"
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          driver: docker-container
          install: true # setup docker build alias
      - name: build image
        run: |
          make BUILD_IN_CONTAINER=false loki-image
