---
name: 'create release PR'
on:
  push:
    branches:
      - 'release-[0-9].[0-9].x'
      - 'k[0-9]*'
  workflow_dispatch: {}
permissions:
  contents: 'write'
  issues: 'write'
  pull-requests: 'write'
jobs:
  create-release-pr:
    uses: ./.github/workflows/release-pr.yml
    with:
      release_repo: grafana/loki-release
    secrets:
      GCS_SERVICE_ACCOUNT_KEY: '${{ secrets.BACKEND_ENTERPRISE_DRONE }}'
      GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
